# Generated by Django 3.2.7 on 2021-10-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_framework_sso", "0002_sessiontoken_last_used_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiontoken",
            name="client_id",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
