# Generated by Django 3.2.16 on 2022-12-15 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rest_framework_sso", "0003_sessiontoken_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiontoken",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.RunSQL("UPDATE rest_framework_sso_sessiontoken SET created_by_id = user_id"),
    ]
